# Generated by Django 5.2.5 on 2025-09-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quote_likes_quote_views_quote_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
