# Generated by Django 5.2.5 on 2025-09-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_quote_likes_alter_quote_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='dislikes',
            field=models.BigIntegerField(default=0),
        ),
    ]
