# Generated by Django 5.2.5 on 2025-09-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_quote_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
